// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet_Guichet.Models;

#nullable disable

namespace Projet_Guichet.Migrations
{
    [DbContext(typeof(GuichetContext))]
    [Migration("20260328012121_InitialStatusSetup")]
    partial class InitialStatusSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projet_Guichet.Models.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date");

                    b.Property<decimal>("Solde")
                        .HasColumnType("money");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Compte", (string)null);
                });

            modelBuilder.Entity("Projet_Guichet.Models.Guichet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Guichet", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 19239.1000m
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.OperationAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("GuichetId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("GuichetId");

                    b.HasIndex("TypeId");

                    b.ToTable("OperationAdmin", (string)null);
                });

            modelBuilder.Entity("Projet_Guichet.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Utilisateur client du guichet",
                            Nom = "Utilisateur"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Administrateur du guichet",
                            Nom = "Admin"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Utilisateur Actif",
                            Nom = "Actif"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Utilisateur Bloque",
                            Nom = "Bloque"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Utilisateur Inactif",
                            Nom = "Inactif"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Utilisateur desactive",
                            Nom = "Desactive"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompteId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Montant")
                        .HasColumnType("money");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.HasKey("Id");

                    b.HasIndex("CompteId");

                    b.HasIndex("TypeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeCompte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeCompte", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Compte cheque du client",
                            Nom = "Cheque"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Compte epargne du client",
                            Nom = "Epargne"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Compte Hypothequaire du client",
                            Nom = "Hypothequaire"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Marge de credit du client",
                            Nom = "MargeCredit"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeOperationAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeOperationAdmin", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "charger les interets a la marge de credit",
                            Nom = "InteretsCredit"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Payer les interets au comptes epargne",
                            Nom = "InteretsEpargne"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ajouter de la monaie au guichet",
                            Nom = "RemplirGuichet"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeTransaction", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Depot d'argent dans le compte",
                            Nom = "Depot"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Retrait d'argent dans le compte",
                            Nom = "Retrait"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Paiement de facture dans le compte",
                            Nom = "PaimentFacture"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Transfer de fonds a partir de ce compte",
                            Nom = "TransferEnvoye"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Transfer de fonds a partir de ce compte",
                            Nom = "TransferRecu"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date");

                    b.Property<int>("Nip")
                        .HasColumnType("int")
                        .HasColumnName("NIP");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 100003,
                            Courriel = "leia.organa@gmail.com",
                            DateCreation = new DateOnly(2024, 1, 2),
                            Nip = 1234,
                            Nom = "Organa",
                            Prenom = "Leia",
                            RoleId = 1,
                            StatusId = 1,
                            Telephone = "1234567890"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.Compte", b =>
                {
                    b.HasOne("Projet_Guichet.Models.TypeCompte", "Type")
                        .WithMany("Comptes")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Compte_TypeCompte");

                    b.HasOne("Projet_Guichet.Models.Utilisateur", "Utilisateur")
                        .WithMany("Comptes")
                        .HasForeignKey("UtilisateurId")
                        .IsRequired()
                        .HasConstraintName("FK_Compte_Utilisateurs2");

                    b.Navigation("Type");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Projet_Guichet.Models.OperationAdmin", b =>
                {
                    b.HasOne("Projet_Guichet.Models.Utilisateur", "Admin")
                        .WithMany("OperationAdmins")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("FK_OperationAdmin_Utilisateurs");

                    b.HasOne("Projet_Guichet.Models.Guichet", "Guichet")
                        .WithMany("OperationAdmins")
                        .HasForeignKey("GuichetId")
                        .IsRequired()
                        .HasConstraintName("FK_OperationAdmin_Guichet");

                    b.HasOne("Projet_Guichet.Models.TypeOperationAdmin", "Type")
                        .WithMany("OperationAdmins")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_OperationAdmin_TypeOperationAdmin");

                    b.Navigation("Admin");

                    b.Navigation("Guichet");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Transaction", b =>
                {
                    b.HasOne("Projet_Guichet.Models.Compte", "Compte")
                        .WithMany("Transactions")
                        .HasForeignKey("CompteId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Compte");

                    b.HasOne("Projet_Guichet.Models.TypeTransaction", "Type")
                        .WithMany("Transactions")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_TypeTransaction");

                    b.Navigation("Compte");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Utilisateur", b =>
                {
                    b.HasOne("Projet_Guichet.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Utilisateurs_Roles");

                    b.HasOne("Projet_Guichet.Models.Status", "Status")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Utilisateurs_Status");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Compte", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Guichet", b =>
                {
                    b.Navigation("OperationAdmins");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Status", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeCompte", b =>
                {
                    b.Navigation("Comptes");
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeOperationAdmin", b =>
                {
                    b.Navigation("OperationAdmins");
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeTransaction", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Utilisateur", b =>
                {
                    b.Navigation("Comptes");

                    b.Navigation("OperationAdmins");
                });
#pragma warning restore 612, 618
        }
    }
}
