// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet_Guichet.Models;

#nullable disable

namespace Projet_Guichet.Migrations
{
    [DbContext(typeof(GuichetContext))]
    partial class GuichetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projet_Guichet.Models.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date");

                    b.Property<decimal>("Solde")
                        .HasColumnType("money");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Compte", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            DateCreation = new DateOnly(2024, 1, 5),
                            Solde = 1250.00m,
                            TypeId = 1,
                            UtilisateurId = 100003
                        },
                        new
                        {
                            Id = 102,
                            DateCreation = new DateOnly(2024, 1, 10),
                            Solde = 5400.75m,
                            TypeId = 2,
                            UtilisateurId = 100003
                        },
                        new
                        {
                            Id = 103,
                            DateCreation = new DateOnly(2024, 1, 12),
                            Solde = -450.00m,
                            TypeId = 4,
                            UtilisateurId = 100003
                        },
                        new
                        {
                            Id = 104,
                            DateCreation = new DateOnly(2024, 1, 15),
                            Solde = 85.20m,
                            TypeId = 1,
                            UtilisateurId = 100004
                        },
                        new
                        {
                            Id = 105,
                            DateCreation = new DateOnly(2024, 1, 2),
                            Solde = 150000.00m,
                            TypeId = 3,
                            UtilisateurId = 100004
                        },
                        new
                        {
                            Id = 106,
                            DateCreation = new DateOnly(2024, 1, 20),
                            Solde = 2100.00m,
                            TypeId = 1,
                            UtilisateurId = 100005
                        },
                        new
                        {
                            Id = 107,
                            DateCreation = new DateOnly(2024, 1, 22),
                            Solde = 10.50m,
                            TypeId = 2,
                            UtilisateurId = 100005
                        },
                        new
                        {
                            Id = 108,
                            DateCreation = new DateOnly(2024, 1, 25),
                            Solde = -1200.30m,
                            TypeId = 4,
                            UtilisateurId = 100005
                        },
                        new
                        {
                            Id = 109,
                            DateCreation = new DateOnly(2024, 2, 1),
                            Solde = 300.00m,
                            TypeId = 1,
                            UtilisateurId = 100003
                        },
                        new
                        {
                            Id = 110,
                            DateCreation = new DateOnly(2024, 2, 5),
                            Solde = 0.00m,
                            TypeId = 2,
                            UtilisateurId = 100004
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.Guichet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Guichet", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 20000.00m
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.OperationAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GuichetId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("GuichetId");

                    b.HasIndex("TypeId");

                    b.ToTable("OperationAdmin", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 801,
                            AdminId = 100003,
                            Date = new DateOnly(2024, 2, 1),
                            Description = "Ouverture du guichet et vérification initiale",
                            GuichetId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 802,
                            AdminId = 100003,
                            Date = new DateOnly(2024, 2, 5),
                            Description = "Remplissage du guichet : +10 000.00$",
                            GuichetId = 1,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 803,
                            AdminId = 100003,
                            Date = new DateOnly(2024, 2, 10),
                            Description = "Blocage de l'utilisateur ID 100005 (Tentatives échouées)",
                            GuichetId = 1,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 804,
                            AdminId = 100003,
                            Date = new DateOnly(2024, 2, 28),
                            Description = "Calcul et versement des intérêts mensuels (1%)",
                            GuichetId = 1,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 805,
                            AdminId = 100003,
                            Date = new DateOnly(2024, 3, 1),
                            Description = "Maintenance préventive du lecteur de cartes",
                            GuichetId = 1,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 806,
                            AdminId = 100003,
                            Date = new DateOnly(2024, 3, 5),
                            Description = "Collecte des intérêts sur marges de crédit (5%)",
                            GuichetId = 1,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 807,
                            AdminId = 100003,
                            Date = new DateOnly(2024, 3, 10),
                            Description = "Création du nouveau compte Chèque pour Utilisateur 100004",
                            GuichetId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 808,
                            AdminId = 100003,
                            Date = new DateOnly(2024, 3, 12),
                            Description = "Déblocage de l'utilisateur ID 100005",
                            GuichetId = 1,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 809,
                            AdminId = 100003,
                            Date = new DateOnly(2024, 3, 15),
                            Description = "Remplissage du guichet : +5 000.00$",
                            GuichetId = 1,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 810,
                            AdminId = 100003,
                            Date = new DateOnly(2024, 3, 20),
                            Description = "Audit de fin de période effectué sans erreurs",
                            GuichetId = 1,
                            TypeId = 1
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrateur",
                            Nom = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Client",
                            Nom = "Utilisateur"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Utilisateur Actif",
                            Nom = "Actif"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Utilisateur Bloque",
                            Nom = "Bloque"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Utilisateur Inactif",
                            Nom = "Inactif"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Utilisateur desactive",
                            Nom = "Desactive"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompteId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Montant")
                        .HasColumnType("money");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.HasKey("Id");

                    b.HasIndex("CompteId");

                    b.HasIndex("TypeId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 501,
                            CompteId = 101,
                            Date = new DateOnly(2024, 2, 1),
                            Description = "Dépôt initial au guichet",
                            Montant = 500.00m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 502,
                            CompteId = 101,
                            Date = new DateOnly(2024, 2, 5),
                            Description = "Retrait guichet automatique",
                            Montant = -40.00m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 503,
                            CompteId = 102,
                            Date = new DateOnly(2024, 2, 2),
                            Description = "Transfert de fonds externe",
                            Montant = 2000.00m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 504,
                            CompteId = 103,
                            Date = new DateOnly(2024, 2, 28),
                            Description = "Frais d'intérêt sur marge (5%)",
                            Montant = -22.50m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 505,
                            CompteId = 104,
                            Date = new DateOnly(2024, 2, 10),
                            Description = "Paiement facture Hydro-Québec",
                            Montant = -112.45m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 506,
                            CompteId = 105,
                            Date = new DateOnly(2024, 2, 1),
                            Description = "Versement hypothécaire mensuel",
                            Montant = 1000.00m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 507,
                            CompteId = 106,
                            Date = new DateOnly(2024, 2, 12),
                            Description = "Retrait guichet",
                            Montant = -100.00m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 508,
                            CompteId = 107,
                            Date = new DateOnly(2024, 2, 15),
                            Description = "Dépôt chèque cadeau",
                            Montant = 50.00m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 509,
                            CompteId = 108,
                            Date = new DateOnly(2024, 2, 28),
                            Description = "Intérêts sur découvert",
                            Montant = -60.01m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 510,
                            CompteId = 102,
                            Date = new DateOnly(2024, 2, 28),
                            Description = "Intérêts épargne ajoutés (1%)",
                            Montant = 54.01m,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 511,
                            CompteId = 101,
                            Date = new DateOnly(2024, 3, 1),
                            Description = "Paiement Vidéotron",
                            Montant = -65.00m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 512,
                            CompteId = 104,
                            Date = new DateOnly(2024, 3, 2),
                            Description = "Retrait guichet rapide",
                            Montant = -20.00m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 513,
                            CompteId = 106,
                            Date = new DateOnly(2024, 3, 5),
                            Description = "Dépôt direct Employeur",
                            Montant = 1200.00m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 514,
                            CompteId = 109,
                            Date = new DateOnly(2024, 3, 5),
                            Description = "Dépôt initial",
                            Montant = 300.00m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 515,
                            CompteId = 103,
                            Date = new DateOnly(2024, 3, 6),
                            Description = "Retrait sur marge",
                            Montant = -50.00m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 516,
                            CompteId = 110,
                            Date = new DateOnly(2024, 3, 7),
                            Description = "Ouverture de compte",
                            Montant = 10.00m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 517,
                            CompteId = 105,
                            Date = new DateOnly(2024, 3, 8),
                            Description = "Paiement taxes municipales",
                            Montant = -450.00m,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 518,
                            CompteId = 102,
                            Date = new DateOnly(2024, 3, 10),
                            Description = "Retrait vacances",
                            Montant = -500.00m,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 519,
                            CompteId = 108,
                            Date = new DateOnly(2024, 3, 12),
                            Description = "Remboursement partiel dette",
                            Montant = 200.00m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 520,
                            CompteId = 101,
                            Date = new DateOnly(2024, 3, 15),
                            Description = "Frais de service mensuel",
                            Montant = -10.00m,
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeCompte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeCompte", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Compte chèque",
                            Nom = "Cheque"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Compte épargne",
                            Nom = "Epargne"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Compte Hypothéquaire",
                            Nom = "Hypothequaire"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Marge de credit",
                            Nom = "MargeCredit"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeOperationAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeOperationAdmin", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "charger les intérêts a la marge de credit",
                            Nom = "InteretsCredit"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Payer les intérêts au comptes epargne",
                            Nom = "InteretsEpargne"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ajouter de la monaie au guichet",
                            Nom = "RemplirGuichet"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Prélevement hypothéquaire executé par l'admin",
                            Nom = "PrelevementHypothequaire"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeTransaction", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dépot",
                            Nom = "Depot"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Retrait",
                            Nom = "Retrait"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Paiement de facture",
                            Nom = "PaimentFacture"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Transfer de fonds a partir du compte",
                            Nom = "TransferEnvoye"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Transfer de fonds reçu par le compte",
                            Nom = "TransferRecu"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Intérêts ajoutés au solde du compte",
                            Nom = "Interets"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Prélevement hypothéquaire fait au compte",
                            Nom = "PrelevementHypothequaire"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("DateCreation")
                        .HasColumnType("date");

                    b.Property<int>("Nip")
                        .HasColumnType("int")
                        .HasColumnName("NIP");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 100003,
                            Courriel = "leia.organa@gmail.com",
                            DateCreation = new DateOnly(2024, 1, 2),
                            Nip = 1234,
                            Nom = "Organa",
                            Prenom = "Leia",
                            RoleId = 1,
                            StatusId = 1,
                            Telephone = "1234567890"
                        },
                        new
                        {
                            Id = 100004,
                            Courriel = "luke.skywalker@gmail.com",
                            DateCreation = new DateOnly(2023, 10, 2),
                            Nip = 1234,
                            Nom = "Skywalker",
                            Prenom = "Luke",
                            RoleId = 2,
                            StatusId = 1,
                            Telephone = "1234567890"
                        },
                        new
                        {
                            Id = 100005,
                            Courriel = "han.solo@gmail.com",
                            DateCreation = new DateOnly(1999, 11, 2),
                            Nip = 1234,
                            Nom = "Solo",
                            Prenom = "Han",
                            RoleId = 2,
                            StatusId = 1,
                            Telephone = "1234567890"
                        },
                        new
                        {
                            Id = 100006,
                            Courriel = "lando.calrissian@gmail.com",
                            DateCreation = new DateOnly(2009, 11, 16),
                            Nip = 1234,
                            Nom = "Calrissian",
                            Prenom = "Lando",
                            RoleId = 2,
                            StatusId = 1,
                            Telephone = "1234567890"
                        },
                        new
                        {
                            Id = 100007,
                            Courriel = "darth.vader@gmail.com",
                            DateCreation = new DateOnly(1993, 4, 3),
                            Nip = 1234,
                            Nom = "Vader",
                            Prenom = "Darth",
                            RoleId = 2,
                            StatusId = 1,
                            Telephone = "1234567890"
                        });
                });

            modelBuilder.Entity("Projet_Guichet.Models.Compte", b =>
                {
                    b.HasOne("Projet_Guichet.Models.TypeCompte", "Type")
                        .WithMany("Comptes")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Compte_TypeCompte");

                    b.HasOne("Projet_Guichet.Models.Utilisateur", "Utilisateur")
                        .WithMany("Comptes")
                        .HasForeignKey("UtilisateurId")
                        .IsRequired()
                        .HasConstraintName("FK_Compte_Utilisateurs2");

                    b.Navigation("Type");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Projet_Guichet.Models.OperationAdmin", b =>
                {
                    b.HasOne("Projet_Guichet.Models.Utilisateur", "Admin")
                        .WithMany("OperationAdmins")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("FK_OperationAdmin_Utilisateurs");

                    b.HasOne("Projet_Guichet.Models.Guichet", "Guichet")
                        .WithMany("OperationAdmins")
                        .HasForeignKey("GuichetId")
                        .IsRequired()
                        .HasConstraintName("FK_OperationAdmin_Guichet");

                    b.HasOne("Projet_Guichet.Models.TypeOperationAdmin", "Type")
                        .WithMany("OperationAdmins")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_OperationAdmin_TypeOperationAdmin");

                    b.Navigation("Admin");

                    b.Navigation("Guichet");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Transaction", b =>
                {
                    b.HasOne("Projet_Guichet.Models.Compte", "Compte")
                        .WithMany("Transactions")
                        .HasForeignKey("CompteId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Compte");

                    b.HasOne("Projet_Guichet.Models.TypeTransaction", "Type")
                        .WithMany("Transactions")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_TypeTransaction");

                    b.Navigation("Compte");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Utilisateur", b =>
                {
                    b.HasOne("Projet_Guichet.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Utilisateurs_Roles");

                    b.HasOne("Projet_Guichet.Models.Status", "Status")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Utilisateurs_Status");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Compte", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Guichet", b =>
                {
                    b.Navigation("OperationAdmins");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Status", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeCompte", b =>
                {
                    b.Navigation("Comptes");
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeOperationAdmin", b =>
                {
                    b.Navigation("OperationAdmins");
                });

            modelBuilder.Entity("Projet_Guichet.Models.TypeTransaction", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Projet_Guichet.Models.Utilisateur", b =>
                {
                    b.Navigation("Comptes");

                    b.Navigation("OperationAdmins");
                });
#pragma warning restore 612, 618
        }
    }
}
